window.WALKS = {
  spine: [
    {
      t: "The whole stack",
      b: "",
      pl: "Where we end up",
      p: "Stones, notes, reserves, a reserve currency, then fiat. A human economy sitting on promises that point up.",
      sl: "Why it exists",
      s: "None of it is needed on day one. Every layer is there because the one below went rigid in a specific way.",
      img: "../images/s_hierarchy.png",
      cap: "Notes between villagers. Reserves between banks. The tortoise at the top.",
    },
    {
      t: "Barter",
      b: "",
      p: "The dairy farmer wants corn when he has no milk. The corn farmer wants meat the butcher will not take corn for. You can only trade when both of you want what the other has, right now.",
      s: "<b>Special gray stones.</b> Hard to collect, so they stand for value. People can transact when they would like.",
      img: "../images/panel1_stones.png",
      cap: "The bull pays the beaver in stones.",
    },
    {
      t: "No stones today",
      b: "Okay, great, now there is money.",
      p: "The bull needs boots now and will have stones after the herd sells. The beaver will not wait. Having stones today is better than having them in a year.",
      s: "<b>Credit, then interest.</b> A promise on paper, plus extra stones for the wait. Time now has a price.",
      img: "../images/panel2_iou.png",
      cap: "The bull turns out an empty pouch. The beaver writes a note.",
    },
    {
      t: "Nobody will lend to a stranger",
      b: "Okay, great, now time has a price.",
      p: "The owl has stones in a jar and no one to lend them to. The bull needs a loan and the shops do not know him. The two never meet.",
      s: "<b>A bank.</b> The raccoon borrows from the owl at three and lends to the bull at five. The spread is a living. Word spreads.",
      img: "../images/panel3_banker.png",
      cap: "The owl brings stones. The raccoon writes a line. The bull takes a note.",
    },
    {
      t: "The vault is not the bank",
      b: "Okay, great, now there is a banker.",
      p: "Stones go in, loans go out, and counting the pile tells the raccoon nothing. One person's deposit is not sitting on a shelf with their name on it.",
      s: "<b>A balance sheet.</b> What the bank owns or is owed, against what it owes. The two lists have to match.",
      img: "../images/n10_balance_sheet.png",
      cap: "Assets on the left, liabilities on the right.",
    },
    {
      t: "A rumour empties the vault",
      b: "Okay, great, now the books balance.",
      p: "The goat sees a queue and gets in it. The raccoon is owed plenty of stones. He does not have them <em>now</em>. Solvent, not liquid. Forced sales destroy value.",
      s: "<b>A backstop, and later a night of grace.</b> A larger bank buys the book. Then banks lend each other overnight. This break never really goes away.",
      img: "../images/panel4_run.png",
      cap: "The goat at the head of the queue. The vault is full of promises, not stones.",
    },
    {
      t: "Carting stones is the job",
      b: "Okay, great, now a bigger bank can catch a small one.",
      p: "Nobody wants to walk around with a sack of stones. Heavy, dangerous, and the shops do not want a back-room pile either.",
      s: "<b>Banknotes.</b> A paper claim on the raccoon. Shops start treating the note as payment. Money is whatever the other party will accept.",
      img: "../images/s_payment.png",
      cap: "The bull leaves the sack and takes a note.",
    },
    {
      t: "Banks owe each other by accident",
      b: "Okay, great, now notes circulate.",
      p: "Stone runners all day. The raccoon pays the badger ten thousand; the badger pays the raccoon eight. Gross settlement is waste, and harvest makes the residual huge.",
      s: "<b>Netting, then overnight deferral.</b> Settle the difference at night. Borrow one night if you must. The overnight rate is born.",
      img: "../images/n2_netting.png",
      cap: "One small pile instead of a hundred trips.",
    },
    {
      t: "Your own deposits are not money to another bank",
      b: "Okay, great, now banks can wait a night.",
      p: "Harvest. The raccoon's vault is empty. He asks the badger for a night. The badger says no. A line the raccoon writes himself means nothing across the table.",
      s: "<b>Reserves from a bank-of-banks.</b> Debt moves up. The tortoise issues money that banks will accept from each other — and, in a crisis, lends when no one else will.",
      img: "../images/s_gridlock.png",
      cap: "The raccoon asks. The badger says no.",
    },
    {
      t: "A village cannot pay another village in its own currency",
      b: "Okay, great, now banks can settle.",
      p: "Gray stones are not money over the mountain. The fox funds the village with red debt until harvests fail. People want out. Four red stones for one black, then default.",
      s: "<b>A reserve currency.</b> Nobody voted. The crow's notes are simply the ones you don't bother to exchange. A habit, then a peg, then a privilege.",
      img: "../images/s_default.png",
      cap: "The fox's empty purse. The others walk away.",
    },
    {
      t: "The promise outgrows the pile",
      b: "Okay, great, now the region settles in black money.",
      p: "Too many claims on too few black stones. Defending convertibility would wreck the crow's own village. The peg cannot be held.",
      s: "<b>Fiat.</b> They stop exchanging notes for stones. Taxes, wages and contracts stay in black money. And yet nothing happened — until trust does.",
      img: "../images/panel6_fiat.png",
      cap: "The crow shuts the vault. The market does not look up.",
    },
  ],

  intermediation: [
    {
      t: "Money",
      b: "",
      p: "The dairy farmer wants corn with no milk to trade. The corn farmer wants meat the butcher will not take corn for. You can only trade when both of you want what the other has, right now.",
      s: "<b>Special gray stones.</b> An abstract unit of value. People transact when they would like, not when barter lines up.",
      img: "../images/panel1_stones.png",
      cap: "The bull hands gray stones to the beaver for a pair of boots.",
    },
    {
      t: "Supply",
      b: "Okay, great, now there is money.",
      p: "If anyone can mint money, it stops being money. Why these stones, and not leaves?",
      s: "<b>Hard to collect.</b> A day's labour at the riverbed. After a flood cuts a new seam, goods cost more and nobody stoops. The supply regulates itself.",
      img: "../images/n1_flood.png",
      cap: "After the flood, gray stones cover the riverbank.",
    },
    {
      t: "Debt",
      b: "Okay, great, now stones are scarce on purpose.",
      p: "The bull raises cows. That takes a year. He must go long stretches without earning stones, and he still needs to eat.",
      s: "<b>Pay later.</b> Write the trade on paper. He has debt; the shop has credit. She will do this for people she knows. Not for strangers.",
      img: "../images/s_debt.png",
      cap: "The bull buys on credit. The details go on a scrap of paper.",
    },
    {
      t: "Interest",
      b: "Okay, great, now some shops will wait.",
      p: "The beaver trusts the bull and still will not wait. He wants tools this year. Having stones today is better than having them in a year.",
      s: "<b>One hundred and five.</b> The extra five stones are for the lost year. Soon every debt is repaid with excess stones. Time has a price.",
      img: "../images/panel2_iou.png",
      cap: "The bull turns out an empty pouch. The beaver writes a note.",
    },
    {
      t: "Bank",
      b: "Okay, great, now time has a price.",
      p: "Most shops will not lend to the bull. The owl has a hundred stones in a jar and no one to lend them to. The two never meet.",
      s: "<b>The raccoon.</b> He borrows from the owl at three and lends to the bull at five. The spread is a living. Word spreads. He calls it a bank.",
      img: "../images/panel3_banker.png",
      cap: "The owl brings stones. The raccoon writes a line. The bull takes a note.",
    },
    {
      t: "Balance",
      b: "Okay, great, now there is a banker.",
      p: "Stones go in, loans go out. Counting the pile tells him nothing. A hundred stones in the vault is not the same as a hundred deposited and four hundred lent.",
      s: "<b>Two lists.</b> Assets: what he owns or is owed. Liabilities: what he owes. They have to match. That is a balance sheet.",
      img: "../images/n10_balance_sheet.png",
      cap: "The raccoon’s two lists: assets and liabilities.",
    },
    {
      t: "Illiquidity",
      b: "Okay, great, now the books balance.",
      p: "The goat sees a queue and gets in it. The raccoon is owed plenty of stones. He does not have them <em>now</em>. Forced sales destroy value.",
      s: "<b>A bigger bank, at a discount.</b> The badger buys the book. The queue stops. Solvent was never the same as liquid.",
      img: "../images/panel4_run.png",
      cap: "The goat at the head of the queue. The vault is full, and slow.",
    },
    {
      t: "Speculation",
      b: "Okay, great, now a larger bank can catch a small one.",
      p: "Villagers can ask for stones back before the loans return. If they all do it at once, the vault is empty. That is the model.",
      s: "<b>Live with it.</b> Some banks safekeep and charge. Some lock withdrawals. The popular model pays you to deposit and lets you leave. A deposit is a speculative investment.",
      img: "../images/s_speculation.png",
      cap: "Villagers deposit stones and may ask for them back before the loans return.",
    },
  ],

  creation: [
    {
      t: "Payment",
      b: "",
      p: "The bull does not want to cart stones around all day. Heavy, dangerous. Shops do not want a back-room pile either.",
      s: "<b>Banknotes.</b> He hands stones to the raccoon and takes paper. Shops were sceptical. Then they liked not storing stones. The note starts to work as payment.",
      img: "../images/s_payment.png",
      cap: "The bull leaves the stones at the bank and takes a note.",
    },
    {
      t: "Settlement",
      b: "Okay, great, now notes circulate.",
      p: "The bull banks with the raccoon, the buyer banks with the badger. A note from one bank lands at the other. Suddenly banks owe each other without meaning to.",
      s: "<b>Gross settlement.</b> Stone runners, as fast as they can. For a moment the badger is lending to the raccoon as an artifact of who paid whom.",
      img: "../images/s_settlement.png",
      cap: "Stone runners between the raccoon’s bank and the badger’s.",
    },
    {
      t: "Residual",
      b: "Okay, great, now every note is run back to stones.",
      p: "The raccoon pays the badger ten thousand; the badger pays the raccoon eight. Gross settlement is costly, dangerous, and stupid.",
      s: "<b>Net the day.</b> At night they settle the difference. Five stones might move. That residual says nothing about the hundreds of trades underneath.",
      img: "../images/n2_netting.png",
      cap: "One small pile instead of a hundred trips.",
    },
    {
      t: "Deferral",
      b: "Okay, great, now they only move the difference.",
      p: "Some nights a bank is good for the money and still cannot pay tonight. Solvent, not liquid. Immediate settlement already destroyed value once, in the run.",
      s: "<b>Tomorrow, plus one night of interest.</b> Banks borrow from each other overnight. The overnight rate is born. Flexibility, on purpose.",
      img: "../images/s_deferral.png",
      cap: "Settle tomorrow, plus one night of interest.",
    },
    {
      t: "Acceptance",
      b: "Okay, great, now banks can wait a night.",
      p: "The beaver has not seen a stone in a while. He is paid in notes, deposits the notes, and goes to bed with a number on a sheet. Is he paid?",
      s: "<b>Money is whatever the other party will accept.</b> Durability and scarcity were never the point. Once he takes the note, he considers himself paid.",
      img: "../images/s_acceptance.png",
      cap: "The beaver tucks the note away. He considers himself paid.",
    },
    {
      t: "Creation",
      b: "Okay, great, now a note is money.",
      p: "A businessman wants a loan. The badger’s vault is nearly empty. She cannot wait for a new deposit. The real risk she manages is the residual at night, not a villager asking for stones.",
      s: "<b>A stroke of the pen.</b> New deposits for him, his debt as an asset. The sheet balances. She did not create stones. He will not ask for any.",
      img: "../images/s_creation.png",
      cap: "The badger writes a new line. The vault barely moves.",
    },
  ],

  centralization: [
    {
      t: "Squeeze",
      b: "",
      p: "Harvest. Field mice want stones, not notes. Stones leave the banks in one direction. On a normal night everyone pays everyone and the residual is small. Tonight it is huge.",
      s: "<b>There isn't a layer for this yet.</b> Overnight loans are supposed to cover it. They only work if someone will lend.",
      img: "../images/n3_harvest.png",
      cap: "Field mice take stones out of town. The vault thins.",
    },
    {
      t: "Gridlock",
      b: "Okay, great, now the residual can blow up.",
      p: "The raccoon’s vault is empty. He asks the badger for a night. The badger says no. A line the raccoon writes himself means nothing across the table. If he cannot pay, the badger cannot pay the next bank.",
      s: "<b>The system freezes.</b> Athena cannot create money Poseidon will accept. They meet in the morning.",
      img: "../images/s_gridlock.png",
      cap: "The raccoon asks. The badger says no.",
    },
    {
      t: "Backstop",
      b: "Okay, great, now we know the rigidity: your own deposits are not money to another bank.",
      p: "You cannot settle a debt by making another one. The badger does not want another promise from another bank.",
      s: "<b>Move the debt up.</b> A clearinghouse inspects the book and issues certificates. Those are money <em>between banks</em>. The raccoon now owes the clearinghouse, not the badger.",
      img: "../images/s_backstop.png",
      cap: "The tortoise issues certificates. Debt moves up.",
    },
    {
      t: "Centralization",
      b: "Okay, great, now there is money between banks.",
      p: "The certificates work. The largest bank runs the process and is also a competitor. A bank-of-banks is the most powerful thing in the village.",
      s: "<b>An official bank-of-banks.</b> The elders take it. Commercial banks, and a central bank. Same job, not a rival’s gavel.",
      img: "../images/s_centralization.png",
      cap: "The elders put the tortoise in charge of a bank-of-banks.",
    },
    {
      t: "Reserves",
      b: "Okay, great, now the tortoise is official.",
      p: "Certificates were ad hoc emergency paper from a club you could leave. Harvest will happen again.",
      s: "<b>Reserves, by law.</b> Every bank keeps an account at the tortoise. A required fraction of deposits. To get more, borrow against assets. Elasticity with a floor.",
      img: "../images/s_reserves.png",
      cap: "Commercial banks must keep reserves at the tortoise.",
    },
    {
      t: "Inflation",
      b: "Okay, great, now banks can always settle by going into debt to the tortoise.",
      p: "Debt in the village grows. The tortoise can always expand its sheet. The stone supply has barely changed. The same cow, more paper.",
      s: "<b>Prices go up.</b> The flood used to do this, and labour at the riverbed slowed down. A stroke of the pen does not get tired.",
      img: "../images/s_inflation.png",
      cap: "The same cow, more paper.",
    },
    {
      t: "Policy",
      b: "Okay, great, now we know the pen can outrun the cows.",
      p: "How do you slow lending without banning it?",
      s: "<b>Price the reserves.</b> Raise the overnight rate, banks hold more reserves and lend less. Cut it, they lend more. One blunt dial for the whole village.",
      img: "../images/n4_rate.png",
      cap: "The tortoise turns the overnight-rate dial.",
    },
    {
      t: "Hierarchy",
      b: "Okay, great, now there is a rate.",
      p: "Villagers settle with stones, notes, deposits. Banks cannot settle with those.",
      s: "<b>Two monies.</b> Notes and deposits are money between villagers. Reserves are money between banks. The tortoise can change the price of credit for everyone, and lend when no one else will.",
      img: "../images/s_hierarchy.png",
      cap: "Notes between villagers. Reserves between banks.",
    },
  ],

  exchange: [
    {
      t: "Currency",
      b: "",
      p: "Over the pass, the fox’s village. Over the river, the heron’s. Each uses its own special stones and calls them money.",
      s: "<b>Call them currency</b> when you are talking across villages. Gray, red, blue. Same idea, not the same money.",
      img: "../images/s_currency.png",
      cap: "Over the pass, the fox. Over the river, the heron. Stones stay gray.",
    },
    {
      t: "Trade",
      b: "Okay, great, now there are other monies.",
      p: "The bull wants the fox’s pottery. He only has gray stones. Gray is not money in the fox’s village.",
      s: "<b>Take it anyway, with a markup.</b> They can spend gray later, or swap it. Trade happens. It stays limited, because the inconvenience is real.",
      img: "../images/s_trade.png",
      cap: "The bull pays the fox in gray stones, with a markup.",
    },
    {
      t: "Exchange",
      b: "Okay, great, now gray can buy red pottery.",
      p: "Merchants end up holding stones they do not want. The inverse pile sits over the mountain.",
      s: "<b>A currency trader.</b> She buys the leftover red with gray, walks the pass, and buys leftover gray with red. She quotes a rate, plus a spread.",
      img: "../images/s_exchange.png",
      cap: "A traveler swaps one village’s stones for another’s.",
    },
    {
      t: "Correspondence",
      b: "Okay, great, now there is a rate.",
      p: "Carting stones between villages is the same old problem: heavy, dangerous, slow.",
      s: "<b>Trade banknotes instead.</b> Banks open accounts with each other, warehouse foreign currency, collect a fee. Correspondent banking. Trade starts creating debts between banking systems.",
      img: "../images/s_correspondence.png",
      cap: "The raccoon takes a foreign note and warehouses it.",
    },
    {
      t: "Exposure",
      b: "Okay, great, now a gray bank can accept a red note.",
      p: "That red note is a promise from another village. There is no tortoise above villages. You cannot create their money or enforce their debts.",
      s: "<b>Watch the other village.</b> A foreign currency is only as good as the place that issued it. Residual payments between systems are usually small — until they are not.",
      img: "../images/s_exposure.png",
      cap: "No central bank above villages. The tortoise watches.",
    },
    {
      t: "Default",
      b: "Okay, great, now the risk has a name.",
      p: "The fox funds the village with bonds. Harvests fail, taxes dwindle. People swap red for black. Two red for one black, then three, then four. Importing gets expensive.",
      s: "<b>They stop paying.</b> Creating more red money would be inflation. The fox’s village defaults. The rigidity: a village cannot settle by making more of its own currency.",
      img: "../images/s_default.png",
      cap: "The fox’s empty purse. Four gray stones for one black note.",
    },
    {
      t: "Reserve",
      b: "Okay, great, now we have seen a village fail.",
      p: "Nobody thought black stones were perfectly safe. They just preferred them to red. The crow’s village is the richest, the fairest, the one with a military.",
      s: "<b>She doesn’t bother to exchange it.</b> A black note is accepted and put away. In a crisis, everyone runs to it. Central bankers start calling black money the reserve currency.",
      img: "../images/s_reserve.png",
      cap: "She pockets the black note and never walks to the exchange booth.",
    },
  ],

  fiat: [
    {
      t: "Devaluation",
      b: "",
      p: "Another village makes clothes and cannot export them. Prices at home are too high relative to the crow’s.",
      s: "<b>Cheapen the money.</b> Expand the sheet, buy foreign currency, purple clothes get cheaper in black terms. Exports rise, imports hurt. Others answer with tariffs. A race.",
      img: "../images/s_devaluation.png",
      cap: "Cheaper clothes arrive. The crow’s own stall sits unsold.",
    },
    {
      t: "Conference",
      b: "Okay, great, now villages are cheapening money to win trade.",
      p: "Devaluations, tariffs, defaults. No backstop between banking systems. Trade is brittle.",
      s: "<b>Write it down.</b> Black money is the official reserve. One black note = thirty-five black stones. Everyone pegs to black. A clearinghouse for central banks, in case a peg needs a night of grace.",
      img: "../images/s_conference.png",
      cap: "The crow, the fox, the heron, and the tortoise write the peg down.",
    },
    {
      t: "Privilege",
      b: "Okay, great, now the peg is official.",
      p: "Other villages have to make and sell goods to get the money used in trade.",
      s: "<b>The crow issues it.</b> People want to hold black notes and black bonds. Debt is cheaper. Public programs are easier. Black villagers buy cheap goods from everywhere.",
      img: "../images/s_privilege.png",
      cap: "The crow issues paper and takes real goods.",
    },
    {
      t: "Dilemma",
      b: "Okay, great, now black money is the thing everyone holds.",
      p: "The more successful it is, the more claims pile up against a pile of black stones. Is every note really worth thirty-five stones?",
      s: "<b>Success is the trap.</b> Convertibility gets harder the more the world wants the promise. Same rigidity as the goat in the queue, one level up.",
      img: "../images/s_dilemma.png",
      cap: "Claims for black money pile up. The stones do not.",
    },
    {
      t: "Float",
      b: "Okay, great, now the peg is a run waiting.",
      p: "Defending convertibility means making black money expensive — buying it back, or raising the rate. That would wreck the crow’s own village. There is more black money than any other currency to buy it with.",
      s: "<b>Stop converting.</b> Notes still trade. The price in stones is no longer fixed. It floats.",
      img: "../images/s_float.png",
      cap: "Convertibility ends. Trading does not.",
    },
    {
      t: "Fiat",
      b: "Okay, great, now the floor is gone.",
      p: "A black note is a piece of paper that cannot be exchanged for special black stones. Why does anyone still take it?",
      s: "<b>And yet nothing happened.</b> Taxes, wages, contracts, reserves — still in black money. The crow’s village is still the one you trust. Within reason they can create money. They cannot create eggs. The floor was a promise. The building was never resting on it.",
      img: "../images/panel6_fiat.png",
      cap: "The crow shuts the vault. The market does not look up.",
    },
  ],

  hierarchy: [
    {
      t: "The pattern",
      b: "",
      pl: "The rigidity",
      p: "A villager could not settle a debt by making more promises. A bank could not settle a debt by creating more of its own deposits. One village could not settle a debt by creating more of its own currency.",
      sl: "The move",
      s: "<b>Debt moves up.</b> Banks above stones. The tortoise above banks. A reserve currency above villages. At each level, money is whatever the counterparty accepts as final — often a promise from the level above.",
      img: "../images/s_hierarchy.png",
      cap: "Notes between villagers. Reserves between banks. The tortoise at the top.",
    },
    {
      t: "The floor was a promise",
      b: "Okay, great, now the stack has a top.",
      pl: "What it rests on",
      p: "The crow sat on a promise to convert notes into black stones. That too was just a promise. They decreed, by fiat, that black money just <em>is</em>.",
      sl: "Until it doesn’t",
      s: "<b>Trust can erode.</b> Bad governance, corruption, poor fiscal policy, competition. For now, black money is the best money in the world.",
      img: "../images/n9_balance.png",
      cap: "Notes on one pan, bread and boots on the other.",
    },
  ],
};
